name: C/C++ CI

on: 
  push:
  pull_request:

jobs:
  macos-static-build:
    runs-on: macos-latest
    steps:
    - name: Install pkg-config dependency
      run: brew install pkg-config;
           export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:${HOME}/prog/lib/pkgconfig
    - name: Update bash
      run: brew install bash
    - name: Fecth CoinBrew
      run: wget -nH https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew;
           chmod u+x coinbrew;
           ./coinbrew fetch Cbc:${GITHUB_REF##*/} --no-prompt
    - name: Set environment variables (for building CBC)
      run: export OSX_VERSION="10.9"; 
           export MACOSX_DEPLOYMENT_TARGET="10.9";
           export CFLAGS="-fPIC -O3 -DNDEBUG -DCBC_THREAD -ffast-math -mmacosx-version-min=10.9 -static";
           export CXXFLAGS="-fPIC -O3 -DNDEBUG -DCBC_THREAD -ffast-math -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.9 -static";
           export F77FLAGS="-fPIC -O3 -DNDEBUG -DCBC_THREAD -ffast-math"; export LDFLAGS="-fPIC -O3 -DNDEBUG -ffast-math";
           export DYLD_LIBRARY_PATH="${HOME}/prog/lib:${DYLD_LIBRARY_PATH}";
    - name: Build static CBC using CoinBrew
      run: sudo ./coinbrew build --prefix=${HOME}/prog Cbc:${GITHUB_REF##*/} 
                                 --without-asl --without-mumps 
                                 --disable-shared --enable-static --enable-cbc-parallel 
                                 --no-prompt --verbosity=4 --parallel-jobs=2 --tests none
    - name: Build shared library for C Interface
      run: sudo clang++ -shared ${CXXFLAGS} -o ${HOME}/prog/lib/cbc-c-darwin-x86-64.dylib
                        -I${HOME}/prog/include/coin-or/ -I${HOME}/prog/include/coin/ -L${HOME}/prog/lib
                        ./Cbc/src/Cbc_C_Interface.cpp
                        -lCbcSolver -lCbc -lCgl -lOsiClp -lClpSolver -lClp -lOsi -lCoinUtils -lCoinGlpk -lOsiCbc
                        -lbz2 -lz -llapack -lreadline -lm
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: cbc-darwin-x86-64
    #     path: /Users/runner/prog
    - uses: actions/upload-artifact@v2
      with:
        name: cbc-c-darwin-x86-64
        path: /Users/runner/prog/lib/cbc-c-darwin-x86-64.dylib

  ubuntu-xenial-static-build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: download GCC 10.1 with static libraries
        run: cd /opt ; wget -nH www.decom.ufop.br/haroldo/files/gcc-xenial-x86-64.tar.xz ; tar Jxf gcc-xenial-x86-64.tar.xz 
      - name: build nauty
        run: export PATH=/opt/gcc/bin/:$PATH ; export IDIR=/home/runner/prog/; cd deps/nauty ;  g++ --version ;
             export CFLAGS="-O3 -fPIC" ; ./configure --prefix=$IDIR --enable-static --disable-shared --enable-generic ; 
             make -j 2 ;  mkdir -p ${IDIR}/include ; mkdir -p ${IDIR}/include/nauty ;
             mkdir -p ${IDIR}/lib ; cp *.h ${IDIR}/include/nauty/ ; cp *.a ${IDIR}/lib/ ; cp nauty.a ${IDIR}/lib/libnauty.a ; cd ../../
      - name: build zlib
        run:  export PATH=/opt/gcc/bin/:$PATH ; export IDIR=/home/runner/prog/ ;
              cd deps/zlib/zlib-1.2.11/ ; ./configure --prefix=${IDIR} --static ; make -j 2 ; make install ; cd ../../../
              #      - name: build blas
              # run: export PATH=/opt/gcc/bin/:$PATH ; export IDIR=/home/runner/prog/; 
              # cd deps/blas/ ; libtoolize ; automake -a ; aclocal ; ./configure --prefix=${IDIR} --enable-static ; make -j 2 ; make install ; cd ../../
      - name: build metis
        run: export PATH=/opt/gcc/bin/:$PATH ; export IDIR=/home/runner/prog/;
             git clone https://github.com/coin-or-tools/ThirdParty-Metis.git ; cd ThirdParty-Metis ; ./get.Metis ; 
             export CFLAGS="-O3 -DNDEBUG " ; export LDFLAGS="" ; 
             ./configure --prefix=${IDIR} --disable-shared --enable-static ; make -j 2 ; make install ; cd ..
      - name: get coinbrew
        run: wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew ; chmod u+x ./coinbrew
      - name: Build Cbc with coinbrew
        run: export PATH=/opt/gcc/bin/:$PATH ; export IDIR=/home/runner/prog/;
             ls -l ${IDIR}/lib/ ; export LDFLAGS="-static -static-libgcc -static-libstdc++ -static-libgfortran  -L${IDIR}/lib/" ; 
             export CXXFLAGS="-O3 -DNDEBUG  -I${IDIR}/include/ -I${IDIR}/include/coin-or/ -fprefetch-loop-arrays" ; 
             export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:${IDIR}/lib/pkgconfig ; ./coinbrew build Cbc@master --without-glpk --without-asl --without-mumps 
             --with-nauty-cflags="-I${IDIR}/include/" --with-nauty-lflags="-L${IDIR}/lib/ -lnauty"
             --disable-shared --enable-static --enable-cbc-parallel --tests none --verbosity=4 --prefix=${IDIR}/
      - name: Build shared library
        run: export PATH=/opt/gcc/bin/:$PATH ; export IDIR=/home/runner/prog/; export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:${IDIR}/lib/pkgconfig ; 
             g++ -shared -o ${IDIR}/lib/cbc-c-linux-x86-64.so
             `pkg-config --cflags cbc cgl osi-clp clp osi coinutils` -fPIC -O3 -DNDEBUG  -I${IDIR}/include/coin-or/ -fprefetch-loop-arrays
                        /home/runner/work/cbc-binaries/cbc-binaries/Cbc/src/Cbc_C_Interface.cpp
                        `pkg-config --libs cbc cgl osi-clp clp osi coinutils`
      - uses: actions/upload-artifact@v2
        with:
          name: cbc-c-linux-x86-64
          path: /home/runner/prog/lib/cbc-c-linux-x86-64.so

  windows-build:
    runs-on: windows-2016
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v1
        with:
          msystem: MINGW64
          update: true
          install: git base-devel gcc mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-toolchain
      - name: create install dir
        run: mkdir -p /d/a/prog/ ; mkdir -p /d/a/prog/include ; mkdir -p /d/a/prog/lib
      - name: install nauty
        run: cd deps/nauty ; export CFLAGS="-O3 -fPIC" ; ./configure --host=x86_64-w64-mingw32 --prefix=/mingw64 --enable-static --disable-shared --enable-generic ; 
             make -j 2 ; mkdir -p /d/a/prog/include/nauty ;
             cp *.h /d/a/prog/include/nauty/ ; cp *.a /d/a/prog/lib/ ; cp nauty.a /d/a/prog/lib/libnauty.a ; cd ../../
      - name: build metis
        run: git clone https://github.com/coin-or-tools/ThirdParty-Metis.git ; cd ThirdParty-Metis ; ./get.Metis ; 
             export CFLAGS="-O3 -DNDEBUG -flto" ; export LDFLAGS="-flto" ; 
             ./configure --prefix=/d/a/prog/ --disable-shared --enable-static ; make -j 2 ; make install ; cd ..
      - name: build zlib
        run:  cd deps/zlib/zlib-1.2.11/ ; ./configure --prefix=/d/a/prog/ --static ; make -j 2 ; make install ; cd ../../../
      - name: build blas
        run: cd deps/blas/ ; libtoolize ; ./configure --host=x86_64-w64-mingw32 --prefix=/d/a/prog/ --enable-static ; make -j 2 ; make install ; cd ../../
        #- name: build lapack
        #run: git clone https://github.com/coin-or-tools/ThirdParty-Lapack.git ; cd ThirdParty-Lapack/ ; ./get.Lapack  ;
        #     ./configure --prefix=/d/a/prog/ --disable-shared --enable-static ; make -j 2 ; make install ; cd ..
      - name: get coinbrew
        run: wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew ; chmod u+x ./coinbrew
      - name: fetching Cbc with coinbrew
        run: ./coinbrew fetch Cbc@master ; ls -l
      - name: Build Cbc with coinbrew
        run: ls -l /d/a/prog/lib/ ; export LDFLAGS="-static -static-libgcc -static-libstdc++ -static-libgfortran -flto -L/d/a/prog/lib/" ; 
             export CXXFLAGS="-O3 -DNDEBUG -flto -I/d/a/prog/include/coin-or/ -fprefetch-loop-arrays" ; 
             export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/d/a/prog/lib/pkgconfig ; ./coinbrew build Cbc@master --host=x86_64-w64-mingw32 --without-glpk --without-asl --without-mumps 
             --with-nauty-cflags="-I/d/a/prog/include/" --with-nauty-lflags="-L/d/a/prog/lib/ -lnauty"
                                         --disable-shared --enable-static --enable-cbc-parallel --tests none --verbosity=4 --prefix=/d/a/prog/
      - name: Build shared library
        run:  export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/d/a/prog/lib/pkgconfig ; x86_64-w64-mingw32-g++ -shared -o /d/a/prog/lib/cbc-c-windows-x86-64.dll
                        `pkg-config --cflags cbc cgl osi-clp clp osi coinutils` -O3 -DNDEBUG -flto -I/d/a/prog/include/coin-or/ -fprefetch-loop-arrays
                        /d/a/cbc-binaries/cbc-binaries/Cbc/src/Cbc_C_Interface.cpp
                        `pkg-config --libs cbc cgl osi-clp clp osi coinutils`
      - uses: actions/upload-artifact@v2
        with:
          name: cbc-c-windows-x86-64
          path: d:\a\prog\lib\cbc-c-windows-x86-64.dll
