name: C/C++ CI

on: 
  push:
  pull_request:

jobs:
  windows-build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Install MSYS2
        run: choco install msys2        
      - name: start build
        run: C:\tools\msys64\usr\bin\bash -lc "ls ; ./build-windows.sh"

