name: C/C++ CI

on: 
  push:
  pull_request:

jobs:
  windows-build:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - uses: numworks/setup-msys2@v1
      - name: update msys2
        run: msys2do pacman -Syu  --noconfirm
      - name: start build
        run: msys2do ./build-windows.sh

