name: C/C++ CI

on: 
  push:
  pull_request:

jobs:
  windows-build:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - name: start build
        uses: numworks/setup-msys2@v1
        run: msys2do ./build-windows.sh

